import { acsmlink, acspolink, agilebootcamplink, agileleaderlink, ailink, blockchainessenlink, blockchainfoundlink, catentacclink, cloudtechlink, cloudvirlink, csmlink, cspolink, cspsmlink, devopslink, icagilelink, icpacclink, icpapmlink, icpatflink, icpbaflink, icpcatlink, icpentlink, icplealink, interthingslink, pmplink, polink, prince2link, psm1link, psm2link, pspo1link, psycholink, safeagilelink, safepopmlink, safesmlink, sasmlink, scrumatscalelink, smclink, sminterlink, smlink, spoclink } from "modules/commanmodules/Pagelinks";

export const CityOptions = [
  { key: 0, text: 'All' },
  { key: 1, text: 'Pune' },
  { key: 2, text: 'Mumbai' },
  { key: 3, text: 'Bangalore' },
  { key: 4, text: 'Online' },
];
export const CourseOptions = [
  // { key: 0, text: "Title", value: "" },
  {
    key: 1,
    text: 'SAFe 6.0 Agilist (Leading SAFe)',
    TableTitle: 'SAFe Agilist Ce   rtification Training',
    WebLink: safeagilelink
  },
  { key: 2, text: 'SAFe®6.0 Scrum Master Certification', TableTitle: '', WebLink: safesmlink },
  { key: 3, text: 'SASM Online', TableTitle: 'SAFe Scrum Master Certification Training', WebLink: sasmlink },
  { key: 4, text: 'SAFe®6.0 Product Owner/Manager Training', TableTitle: 'SAFe POPM Certification Training', WebLink: safepopmlink },
  { key: 6, text: 'Scrum@Scale Online', TableTitle: 'Registered Scrum@Scale Practitioner', WebLink: scrumatscalelink },
  { key: 7, text: 'CSM Online', TableTitle: 'Online Certified Scrum Master (CSM) Certification Training Course', WebLink: csmlink },
  { key: 8, text: 'A-CSM Online', TableTitle: 'Advanced (A-CSM) Certified Scrum Master Training Certification', WebLink: acsmlink },
  { key: 9, text: 'SM Online', TableTitle: 'Scrum Master & Product Owner Certifications In Just 1 Online Training!', WebLink: smlink },
  { key: 10, text: 'PSM Online', TableTitle: 'PROFESSIONAL SCRUM MASTER Certification Training Course', WebLink: psm1link },
  { key: 11, text: 'PSM2 Online', TableTitle: 'PROFESSIONAL SCRUM MASTER II Certification Training Course', WebLink: psm2link },
  { key: 12, text: 'CSP-SM Online', TableTitle: 'Certified Scrum Professional ScrumMaster® Certification Training Course', WebLink: cspsmlink },
  { key: 13, text: 'SMC', TableTitle: 'Online Scrum Master Certified (SMC) Certification Training Course', WebLink: smclink },
  { key: 14, text: 'Scrum Master Interview Session', TableTitle: 'Scrum Master Interview Preparation Session', WebLink: sminterlink },
  // { key: 15, text: 'SAFe®6.0 Product Owner/Manager Training', TableTitle: '', WebLink:},
  { key: 16, text: 'CSPO Online', TableTitle: 'Certified Scrum Product Owner® Certification Course', WebLink: cspolink },
  { key: 17, text: 'PSPO Online', TableTitle: 'PROFESSIONAL SCRUM PRODUCT OWNER™ I Course', WebLink: pspo1link },
  { key: 18, text: 'SPO Online', TableTitle: 'Scrum Product Owner Certification Training', WebLink: polink },
  { key: 19, text: 'SPOC', TableTitle: 'Online Scrum Product Owner Certified (SPOC®) Certification Training Course', WebLink: spoclink },
  { key: 20, text: 'ACSPO Online', TableTitle: 'Advanced Certified Scrum Product Owner Certification Training Course', WebLink: acspolink },
  { key: 21, text: 'Master Class (ICP- CAT)+(ICP- ENT)', TableTitle: 'Enterprise Agile Coach Masterclass / Bootcamp', WebLink: agilebootcamplink },
  { key: 22, text: 'Master Class ICP-CAT + ICP-ENT', TableTitle: 'Agile Coach - Shu - Ha- Ri Package / Bootcamp', WebLink: catentacclink },
  { key: 23, text: 'ICP-ACC Online', TableTitle: '', WebLink: icpacclink },
  { key: 24, text: 'ICP- APM', TableTitle: '', WebLink: icpapmlink },
  { key: 25, text: 'ICP- CAT', TableTitle: '', WebLink: icpcatlink },
  { key: 26, text: 'ICP-ENT Online', TableTitle: '', WebLink: icpentlink },
  { key: 27, text: 'Psychological Safety', TableTitle: 'Psychological Safety - The Foundation for Team Performance (Classroom / Online Training)', WebLink: psycholink },
  { key: 28, text: 'Agile Leadership Awareness Workshop', TableTitle: 'Agile Leadership Journey™', WebLink: agileleaderlink },
  { key: 29, text: 'ICP-ATF Online', TableTitle: '', WebLink: icpatflink },
  { key: 30, text: 'ICP-LEA Online', TableTitle: '', WebLink: icplealink },
  { key: 31, text: 'ICP-BAF Online', TableTitle: 'Business Agility Foundations (ICP-BAF) Training Certification', WebLink: icpbaflink },
  { key: 32, text: 'icagile fundamental Online', TableTitle: 'ICAgile Fundamentals Classroom / Online Training Certification', WebLink: icagilelink },
  { key: 33, text: 'Coming Soon', TableTitle: 'DevOps Professional Certification Training Course', WebLink: devopslink },
  { key: 34, text: 'PMP Online', TableTitle: 'Project Management Professional (PMP) Certification', WebLink: pmplink },
  { key: 35, text: 'Prince2 Foundation', TableTitle: 'Prince2', WebLink: prince2link },
  { key: 36, text: 'Internate Of Things', TableTitle: 'Internet of Things Foundation', WebLink: interthingslink },
  { key: 37, text: 'Artificial Intelligence Essentials', TableTitle: 'Artificial Intelligence Essentials', WebLink: ailink },
  { key: 38, text: 'Blockchain Foundation', TableTitle: 'Blockchain Foundation', WebLink: blockchainfoundlink },
  { key: 39, text: 'Cloud Virtualization Essentials', TableTitle: 'Cloud Virtualization Essentials', WebLink: cloudvirlink },
  { key: 40, text: 'Blockchain Essentials', TableTitle: 'Blockchain Essentials', WebLink: blockchainessenlink },
  { key: 41, text: 'Cloud Technology Associate', TableTitle: 'Cloud Technology Associate', WebLink: cloudtechlink },
];
export const TrainerList = [
  { key: 1, text: 'Joel' },
  { key: 2, text: 'Shijo' },
  { key: 3, text: 'Hiren' },
  { key: 4, text: 'Manjunatha MS' },
  { key: 5, text: 'Vijaywade' },
];
export const CocheSubject = [
  { key: 1, text: 'Agile Coach', value: 'Agile Coach' },
  { key: 2, text: 'Career Coach', value: 'Career Coach' },
  { key: 3, text: 'Life Coach', value: 'Life Coach' },
];
export const QuizSubjectList = [
  { key: 1, text: 'SAFE' },
  { key: 2, text: 'Kanban' },
  { key: 3, text: 'Agile Project Management' },
  { key: 4, text: 'Scrum' },
];
export const SpecializationList = [
  { key: 1, text: 'Agile Transformation Expert' },
  { key: 2, text: 'Alternate Medicine Expert' },
  { key: 3, text: 'Career Reinvention Coach' },
  { key: 4, text: 'Certified ACC by LightHouse Coaching' },
  { key: 5, text: 'Corporate Coaching' },
  { key: 6, text: 'Dilemma Coaching' },
  { key: 7, text: 'Enterprise Agile Coaching' },
  { key: 8, text: 'Leadership Coaching' },
  { key: 9, text: 'Lifestyle Coaching' },
  { key: 10, text: 'MBTI Certified Personality Assessor' },
  { key: 11, text: 'Organizational Development Coaching' },
  { key: 12, text: 'Professional Development Coaching' },
  { key: 13, text: 'Psychotherapy &amp;Psychosomatic therapist' },
  { key: 14, text: 'SAFe 5 Program Consultant' },
  { key: 15, text: 'SAFe Agile Coaching' },
  { key: 16, text: 'Work Life Balance Coaching' },
];
export const CountryList = [
  { key: 1, text: 'Germany' },
  { key: 2, text: 'India' },
  { key: 3, text: 'Malaysia' },
  { key: 4, text: 'Portugal' },
  { key: 5, text: 'Singapore' },
  { key: 6, text: 'Slovakia' },
  { key: 7, text: 'Turkey' },
  { key: 8, text: 'United Kingdom' },
  { key: 9, text: 'USA' },
];
export const CertList = [
  { key: 1, text: 'Kanban' },
  { key: 2, text: 'Scrum' },
  { key: 3, text: 'SAFe' },
  { key: 4, text: 'Scrum@Scale' },
  { key: 5, text: 'Six Sigma' },
  { key: 6, text: 'PMP' },
  { key: 7, text: 'PMI-ACP' },
  { key: 8, text: 'Agile Coaching' },
  { key: 9, text: 'DevOps' },
];
