export const CityOptions = [
  { key: 0, text: 'All' },
  { key: 1, text: 'Pune' },
  { key: 2, text: 'Mumbai' },
  { key: 3, text: 'Bangalore' },
  { key: 4, text: 'Online' },
];
export const CourseOptions = [
  // { key: 0, text: "Title", value: "" },
  { key: 1, text: 'SAFe 6.0 Agilist (Leading SAFe)' },
  { key: 2, text: 'SAFe®6.0 Scrum Master Certification' },
  { key: 3, text: 'SASM Online' },
  { key: 4, text: 'SAFe®6.0 Product Owner/Manager Training' },
  { key: 5, text: 'SAFe for Architects (ARCH) Online' },
  { key: 6, text: 'Scrum@Scale Online' },
  { key: 7, text: 'CSM Online' },
  { key: 8, text: 'A-CSM Online' },
  { key: 9, text: 'SM Online' },
  { key: 10, text: 'PSM Online' },
  { key: 11, text: 'PSM2 Online' },
  { key: 12, text: 'CSP-SM Online' },
  { key: 13, text: 'SMC' },
  { key: 14, text: 'Scrum Master Interview Session' },
  { key: 15, text: 'SAFe®6.0 Product Owner/Manager Training' },
  { key: 16, text: 'CSPO Online' },
  { key: 17, text: 'PSPO Online' },
  { key: 18, text: 'SPO Online' },
  { key: 19, text: 'SPOC' },
  { key: 20, text: 'ACSPO Online' },
  { key: 21, text: 'Master Class (ICP- CAT)+(ICP- ENT)' },
  { key: 22, text: 'Master Class ICP-CAT + ICP-ENT' },
  { key: 23, text: 'ICP-ACC Online' },
  { key: 24, text: 'ICP- APM' },
  { key: 25, text: 'ICP- CAT' },
  { key: 26, text: 'ICP-ENT Online' },
  { key: 27, text: 'Psychological Safety' },
  { key: 28, text: 'Agile Leadership Awareness Workshop' },
  { key: 29, text: 'ICP-ATF Online' },
  { key: 30, text: 'ICP-LEA Online' },
  { key: 31, text: 'ICP-BAF Online' },
  { key: 32, text: 'icagile fundamental Online' },
  { key: 33, text: 'Coming Soon' },
  { key: 34, text: 'PMP Online' },
  { key: 35, text: 'Prince2 Foundation' },
  { key: 36, text: 'Internate Of Things' },
  { key: 37, text: 'Artificial Intelligence Essentials' },
  { key: 38, text: 'Blockchain Foundation' },
  { key: 39, text: 'Cloud Virtualization Essentials' },
  { key: 40, text: 'Blockchain Essentials' },
  { key: 41, text: 'Cloud Technology Associate' },
];
export const TrainerList = [
  { key: 1, text: 'Joel' },
  { key: 2, text: 'Shijo' },
  { key: 3, text: 'Hiren' },
  { key: 4, text: 'Manjunatha MS' },
  { key: 5, text: 'Vijaywade' },
];
export const CocheSubject = [
  { key: 1, text: 'Agile Coach', value: 'Agile Coach' },
  { key: 2, text: 'Career Coach', value: 'Career Coach' },
  { key: 3, text: 'Life Coach', value: 'Life Coach' },
];
export const QuizSubjectList = [
  { key: 1, text: 'SAFE' },
  { key: 2, text: 'Kanban' },
  { key: 3, text: 'Agile Project Management' },
  { key: 4, text: 'Scrum' },
];
export const SpecializationList = [
  { key: 1, text: 'Agile Transformation Expert' },
  { key: 2, text: 'Alternate Medicine Expert' },
  { key: 3, text: 'Career Reinvention Coach' },
  { key: 4, text: 'Certified ACC by LightHouse Coaching' },
  { key: 5, text: 'Corporate Coaching' },
  { key: 6, text: 'Dilemma Coaching' },
  { key: 7, text: 'Enterprise Agile Coaching' },
  { key: 8, text: 'Leadership Coaching' },
  { key: 9, text: 'Lifestyle Coaching' },
  { key: 10, text: 'MBTI Certified Personality Assessor' },
  { key: 11, text: 'Organizational Development Coaching' },
  { key: 12, text: 'Professional Development Coaching' },
  { key: 13, text: 'Psychotherapy &amp;Psychosomatic therapist' },
  { key: 14, text: 'SAFe 5 Program Consultant' },
  { key: 15, text: 'SAFe Agile Coaching' },
  { key: 16, text: 'Work Life Balance Coaching' },
];
export const CountryList = [

  { key: 1, text: 'Germany' },
  { key: 2, text: 'India' },
  { key: 3, text: 'Malaysia' },
  { key: 4, text: 'Portugal' },
  { key: 5, text: 'Singapore' },
  { key: 6, text: 'Slovakia' },
  { key: 7, text: 'Turkey' },
  { key: 8, text: 'United Kingdom' },
  { key: 9, text: 'USA' },
]